kind: Service
apiVersion: v1
metadata:
  name: aleph
  labels:
    name: aleph
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    name: frontend-app
  type: LoadBalancerapp
        
---

apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: frontend-app
  labels:
    name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend-app
  template:
    metadata:
      labels:
        name: frontend-app
    spec:
      containers:
      - name: frontend-image
        image: forntend-image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      
  